version: '3.8'

services:
  postgresql:
    image: postgres
    container_name: postgress-db
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./build/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default

  email:
    build:
      context: .
      dockerfile: ./cmd/email/Dockerfile
    container_name: email-service
    networks:
      - default

  todo:
    build:
      context: .
      dockerfile: ./cmd/todo/Dockerfile
    container_name: todo-service
    networks:
      - default

  activity:
    build:
      context: .
      dockerfile: ./cmd/activity/Dockerfile
    container_name: activity-service
    networks:
      - default

  projects:
    build:
      context: .
      dockerfile: ./cmd/projects/Dockerfile
    container_name: projects-service
    ports:
      - "8084:8084"
    networks:
      - default

volumes:
  postgres-data:

networks:
  default:
