version: '3.8'

# The DB credentials that are used by multiple containers
x-common-variables: &common-variables
  POSTGRES_USER: docker
  POSTGRES_PASSWORD: docker
  POSTGRES_HOST: postgresql

services:
  postgresql:
    image: postgres
    container_name: postgress-db
    ports:
      - "5432:5432"
    environment: *common-variables
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./build/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default

  accounts:
    environment: *common-variables
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./cmd/account/Dockerfile
    container_name: accountss-service
    ports:
      - "8085:8085"
    networks:
      - default

#  tasks:
#    environment: *common-variables
#    restart: unless-stopped
#    build:
#      context: .
#      dockerfile: ./cmd/tasks/Dockerfile
#    container_name: task-service
#    ports:
#    - "8081:8081"
#    networks:
#      - default
##
#  activity:
#    environment: *common-variables
#    build:
#      context: .
#      dockerfile: ./cmd/activity/Dockerfile
#    container_name: activity-service
#    ports:
#      - "8082:8082"
#    networks:
#      - default
#
#  projects:
#    environment: *common-variables
#    build:
#      context: .
#      dockerfile: ./cmd/projects/Dockerfile
#    container_name: projects-service
#    ports:
#      - "8084:8084"
#    networks:
#      - default

volumes:
  postgres-data:

networks:
  default:
