version: '3.8'

# The DB credentials that are used by multiple containers
x-common-variables: &common-variables
  POSTGRES_USER: docker
  POSTGRES_PASSWORD: docker

services:
  postgresql:
    image: postgres
    container_name: postgress-db
    environment: *common-variables
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./build/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default

  todo:
    environment: *common-variables
    build:
      context: .
      dockerfile: ./cmd/todo/Dockerfile
    container_name: todo-service
    networks:
      - default

  activity:
    environment: *common-variables
    build:
      context: .
      dockerfile: ./cmd/activity/Dockerfile
    container_name: activity-service
    networks:
      - default

  projects:
    environment: *common-variables
    build:
      context: .
      dockerfile: ./cmd/projects/Dockerfile
    container_name: projects-service
    networks:
      - default

  accounts:
    build:
      context: .
      dockerfile: ./cmd/account/Dockerfile
    environment: *common-variables
    container_name: accountss-service
    networks:
      - default

volumes:
  postgres-data:

networks:
  default:
